//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace RSSReaderWebsite.myCoreService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CoreServiceImplSoap", Namespace="http://tempuri.org/")]
    public partial class CoreServiceImpl : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckValidUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTabOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveTabOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShareTabOperationCompleted;
        
        private System.Threading.SendOrPostCallback RenameTabOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTabsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllSharedTabsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddRSSItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveRSSItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllRSSItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRSSResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRSSResultHTMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllRSSPluginLinkOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CoreServiceImpl() {
            this.Url = global::RSSReaderWebsite.Properties.Settings.Default.RSSReaderWebsite_myCoreService_CoreServiceImpl;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckValidUsernameCompletedEventHandler CheckValidUsernameCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event AddTabCompletedEventHandler AddTabCompleted;
        
        /// <remarks/>
        public event RemoveTabCompletedEventHandler RemoveTabCompleted;
        
        /// <remarks/>
        public event ShareTabCompletedEventHandler ShareTabCompleted;
        
        /// <remarks/>
        public event RenameTabCompletedEventHandler RenameTabCompleted;
        
        /// <remarks/>
        public event GetAllTabsCompletedEventHandler GetAllTabsCompleted;
        
        /// <remarks/>
        public event GetAllSharedTabsCompletedEventHandler GetAllSharedTabsCompleted;
        
        /// <remarks/>
        public event AddRSSItemCompletedEventHandler AddRSSItemCompleted;
        
        /// <remarks/>
        public event RemoveRSSItemCompletedEventHandler RemoveRSSItemCompleted;
        
        /// <remarks/>
        public event GetAllRSSItemsCompletedEventHandler GetAllRSSItemsCompleted;
        
        /// <remarks/>
        public event GetRSSResultCompletedEventHandler GetRSSResultCompleted;
        
        /// <remarks/>
        public event GetRSSResultHTMLCompletedEventHandler GetRSSResultHTMLCompleted;
        
        /// <remarks/>
        public event GetAllRSSPluginLinkCompletedEventHandler GetAllRSSPluginLinkCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckValidUsername", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckValidUsername(string username) {
            object[] results = this.Invoke("CheckValidUsername", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckValidUsernameAsync(string username) {
            this.CheckValidUsernameAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckValidUsernameAsync(string username, object userState) {
            if ((this.CheckValidUsernameOperationCompleted == null)) {
                this.CheckValidUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckValidUsernameOperationCompleted);
            }
            this.InvokeAsync("CheckValidUsername", new object[] {
                        username}, this.CheckValidUsernameOperationCompleted, userState);
        }
        
        private void OnCheckValidUsernameOperationCompleted(object arg) {
            if ((this.CheckValidUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckValidUsernameCompleted(this, new CheckValidUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Register", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Register(string username, string password) {
            object[] results = this.Invoke("Register", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(string username, string password) {
            this.RegisterAsync(username, password, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(string username, string password, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        username,
                        password}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string username, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logout", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Logout() {
            object[] results = this.Invoke("Logout", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        /// <remarks/>
        public void LogoutAsync(object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[0], this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddTab", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddTab(string tabName) {
            object[] results = this.Invoke("AddTab", new object[] {
                        tabName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddTabAsync(string tabName) {
            this.AddTabAsync(tabName, null);
        }
        
        /// <remarks/>
        public void AddTabAsync(string tabName, object userState) {
            if ((this.AddTabOperationCompleted == null)) {
                this.AddTabOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTabOperationCompleted);
            }
            this.InvokeAsync("AddTab", new object[] {
                        tabName}, this.AddTabOperationCompleted, userState);
        }
        
        private void OnAddTabOperationCompleted(object arg) {
            if ((this.AddTabCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTabCompleted(this, new AddTabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveTab", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RemoveTab(int tabid) {
            object[] results = this.Invoke("RemoveTab", new object[] {
                        tabid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveTabAsync(int tabid) {
            this.RemoveTabAsync(tabid, null);
        }
        
        /// <remarks/>
        public void RemoveTabAsync(int tabid, object userState) {
            if ((this.RemoveTabOperationCompleted == null)) {
                this.RemoveTabOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveTabOperationCompleted);
            }
            this.InvokeAsync("RemoveTab", new object[] {
                        tabid}, this.RemoveTabOperationCompleted, userState);
        }
        
        private void OnRemoveTabOperationCompleted(object arg) {
            if ((this.RemoveTabCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveTabCompleted(this, new RemoveTabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShareTab", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ShareTab(int tabid, string userName) {
            object[] results = this.Invoke("ShareTab", new object[] {
                        tabid,
                        userName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ShareTabAsync(int tabid, string userName) {
            this.ShareTabAsync(tabid, userName, null);
        }
        
        /// <remarks/>
        public void ShareTabAsync(int tabid, string userName, object userState) {
            if ((this.ShareTabOperationCompleted == null)) {
                this.ShareTabOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShareTabOperationCompleted);
            }
            this.InvokeAsync("ShareTab", new object[] {
                        tabid,
                        userName}, this.ShareTabOperationCompleted, userState);
        }
        
        private void OnShareTabOperationCompleted(object arg) {
            if ((this.ShareTabCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShareTabCompleted(this, new ShareTabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RenameTab", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RenameTab(int tabid, string newName) {
            object[] results = this.Invoke("RenameTab", new object[] {
                        tabid,
                        newName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RenameTabAsync(int tabid, string newName) {
            this.RenameTabAsync(tabid, newName, null);
        }
        
        /// <remarks/>
        public void RenameTabAsync(int tabid, string newName, object userState) {
            if ((this.RenameTabOperationCompleted == null)) {
                this.RenameTabOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRenameTabOperationCompleted);
            }
            this.InvokeAsync("RenameTab", new object[] {
                        tabid,
                        newName}, this.RenameTabOperationCompleted, userState);
        }
        
        private void OnRenameTabOperationCompleted(object arg) {
            if ((this.RenameTabCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RenameTabCompleted(this, new RenameTabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllTabs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TabDTO[] GetAllTabs() {
            object[] results = this.Invoke("GetAllTabs", new object[0]);
            return ((TabDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTabsAsync() {
            this.GetAllTabsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTabsAsync(object userState) {
            if ((this.GetAllTabsOperationCompleted == null)) {
                this.GetAllTabsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTabsOperationCompleted);
            }
            this.InvokeAsync("GetAllTabs", new object[0], this.GetAllTabsOperationCompleted, userState);
        }
        
        private void OnGetAllTabsOperationCompleted(object arg) {
            if ((this.GetAllTabsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTabsCompleted(this, new GetAllTabsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllSharedTabs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TabDTO[] GetAllSharedTabs() {
            object[] results = this.Invoke("GetAllSharedTabs", new object[0]);
            return ((TabDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSharedTabsAsync() {
            this.GetAllSharedTabsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllSharedTabsAsync(object userState) {
            if ((this.GetAllSharedTabsOperationCompleted == null)) {
                this.GetAllSharedTabsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSharedTabsOperationCompleted);
            }
            this.InvokeAsync("GetAllSharedTabs", new object[0], this.GetAllSharedTabsOperationCompleted, userState);
        }
        
        private void OnGetAllSharedTabsOperationCompleted(object arg) {
            if ((this.GetAllSharedTabsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSharedTabsCompleted(this, new GetAllSharedTabsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddRSSItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddRSSItem(int tabid, string rsslink) {
            object[] results = this.Invoke("AddRSSItem", new object[] {
                        tabid,
                        rsslink});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddRSSItemAsync(int tabid, string rsslink) {
            this.AddRSSItemAsync(tabid, rsslink, null);
        }
        
        /// <remarks/>
        public void AddRSSItemAsync(int tabid, string rsslink, object userState) {
            if ((this.AddRSSItemOperationCompleted == null)) {
                this.AddRSSItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddRSSItemOperationCompleted);
            }
            this.InvokeAsync("AddRSSItem", new object[] {
                        tabid,
                        rsslink}, this.AddRSSItemOperationCompleted, userState);
        }
        
        private void OnAddRSSItemOperationCompleted(object arg) {
            if ((this.AddRSSItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddRSSItemCompleted(this, new AddRSSItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveRSSItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveRSSItem(int rssid) {
            object[] results = this.Invoke("RemoveRSSItem", new object[] {
                        rssid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveRSSItemAsync(int rssid) {
            this.RemoveRSSItemAsync(rssid, null);
        }
        
        /// <remarks/>
        public void RemoveRSSItemAsync(int rssid, object userState) {
            if ((this.RemoveRSSItemOperationCompleted == null)) {
                this.RemoveRSSItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveRSSItemOperationCompleted);
            }
            this.InvokeAsync("RemoveRSSItem", new object[] {
                        rssid}, this.RemoveRSSItemOperationCompleted, userState);
        }
        
        private void OnRemoveRSSItemOperationCompleted(object arg) {
            if ((this.RemoveRSSItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveRSSItemCompleted(this, new RemoveRSSItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllRSSItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RSSItemDTO[] GetAllRSSItems(int tabid) {
            object[] results = this.Invoke("GetAllRSSItems", new object[] {
                        tabid});
            return ((RSSItemDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllRSSItemsAsync(int tabid) {
            this.GetAllRSSItemsAsync(tabid, null);
        }
        
        /// <remarks/>
        public void GetAllRSSItemsAsync(int tabid, object userState) {
            if ((this.GetAllRSSItemsOperationCompleted == null)) {
                this.GetAllRSSItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllRSSItemsOperationCompleted);
            }
            this.InvokeAsync("GetAllRSSItems", new object[] {
                        tabid}, this.GetAllRSSItemsOperationCompleted, userState);
        }
        
        private void OnGetAllRSSItemsOperationCompleted(object arg) {
            if ((this.GetAllRSSItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllRSSItemsCompleted(this, new GetAllRSSItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRSSResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRSSResult(int rssid, int count) {
            object[] results = this.Invoke("GetRSSResult", new object[] {
                        rssid,
                        count});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRSSResultAsync(int rssid, int count) {
            this.GetRSSResultAsync(rssid, count, null);
        }
        
        /// <remarks/>
        public void GetRSSResultAsync(int rssid, int count, object userState) {
            if ((this.GetRSSResultOperationCompleted == null)) {
                this.GetRSSResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRSSResultOperationCompleted);
            }
            this.InvokeAsync("GetRSSResult", new object[] {
                        rssid,
                        count}, this.GetRSSResultOperationCompleted, userState);
        }
        
        private void OnGetRSSResultOperationCompleted(object arg) {
            if ((this.GetRSSResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRSSResultCompleted(this, new GetRSSResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRSSResultHTML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRSSResultHTML(RSSItem rssItem, int count) {
            object[] results = this.Invoke("GetRSSResultHTML", new object[] {
                        rssItem,
                        count});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRSSResultHTMLAsync(RSSItem rssItem, int count) {
            this.GetRSSResultHTMLAsync(rssItem, count, null);
        }
        
        /// <remarks/>
        public void GetRSSResultHTMLAsync(RSSItem rssItem, int count, object userState) {
            if ((this.GetRSSResultHTMLOperationCompleted == null)) {
                this.GetRSSResultHTMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRSSResultHTMLOperationCompleted);
            }
            this.InvokeAsync("GetRSSResultHTML", new object[] {
                        rssItem,
                        count}, this.GetRSSResultHTMLOperationCompleted, userState);
        }
        
        private void OnGetRSSResultHTMLOperationCompleted(object arg) {
            if ((this.GetRSSResultHTMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRSSResultHTMLCompleted(this, new GetRSSResultHTMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllRSSPluginLink", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAllRSSPluginLink() {
            object[] results = this.Invoke("GetAllRSSPluginLink", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllRSSPluginLinkAsync() {
            this.GetAllRSSPluginLinkAsync(null);
        }
        
        /// <remarks/>
        public void GetAllRSSPluginLinkAsync(object userState) {
            if ((this.GetAllRSSPluginLinkOperationCompleted == null)) {
                this.GetAllRSSPluginLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllRSSPluginLinkOperationCompleted);
            }
            this.InvokeAsync("GetAllRSSPluginLink", new object[0], this.GetAllRSSPluginLinkOperationCompleted, userState);
        }
        
        private void OnGetAllRSSPluginLinkOperationCompleted(object arg) {
            if ((this.GetAllRSSPluginLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllRSSPluginLinkCompleted(this, new GetAllRSSPluginLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TabDTO {
        
        private int idField;
        
        private string nameField;
        
        private int ownerIDField;
        
        private string ownerUsernameField;
        
        private int childCountField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int OwnerID {
            get {
                return this.ownerIDField;
            }
            set {
                this.ownerIDField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerUsername {
            get {
                return this.ownerUsernameField;
            }
            set {
                this.ownerUsernameField = value;
            }
        }
        
        /// <remarks/>
        public int ChildCount {
            get {
                return this.childCountField;
            }
            set {
                this.childCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RSSPlugin {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string websiteLinkField;
        
        private string dLLNameField;
        
        private RSSItem[] rSSItemsField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string WebsiteLink {
            get {
                return this.websiteLinkField;
            }
            set {
                this.websiteLinkField = value;
            }
        }
        
        /// <remarks/>
        public string DLLName {
            get {
                return this.dLLNameField;
            }
            set {
                this.dLLNameField = value;
            }
        }
        
        /// <remarks/>
        public RSSItem[] RSSItems {
            get {
                return this.rSSItemsField;
            }
            set {
                this.rSSItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RSSItem {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string rSSLinkField;
        
        private int tabIDField;
        
        private int pluginIDField;
        
        private Tab tabField;
        
        private RSSPlugin rSSPluginField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string RSSLink {
            get {
                return this.rSSLinkField;
            }
            set {
                this.rSSLinkField = value;
            }
        }
        
        /// <remarks/>
        public int TabID {
            get {
                return this.tabIDField;
            }
            set {
                this.tabIDField = value;
            }
        }
        
        /// <remarks/>
        public int PluginID {
            get {
                return this.pluginIDField;
            }
            set {
                this.pluginIDField = value;
            }
        }
        
        /// <remarks/>
        public Tab Tab {
            get {
                return this.tabField;
            }
            set {
                this.tabField = value;
            }
        }
        
        /// <remarks/>
        public RSSPlugin RSSPlugin {
            get {
                return this.rSSPluginField;
            }
            set {
                this.rSSPluginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tab {
        
        private int idField;
        
        private string nameField;
        
        private int userIDField;
        
        private Share[] sharesField;
        
        private RSSItem[] rSSItemsField;
        
        private Account accountField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public Share[] Shares {
            get {
                return this.sharesField;
            }
            set {
                this.sharesField = value;
            }
        }
        
        /// <remarks/>
        public RSSItem[] RSSItems {
            get {
                return this.rSSItemsField;
            }
            set {
                this.rSSItemsField = value;
            }
        }
        
        /// <remarks/>
        public Account Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Share {
        
        private int idField;
        
        private int accountIDField;
        
        private int tabIDField;
        
        private Tab tabField;
        
        private Account accountField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public int TabID {
            get {
                return this.tabIDField;
            }
            set {
                this.tabIDField = value;
            }
        }
        
        /// <remarks/>
        public Tab Tab {
            get {
                return this.tabField;
            }
            set {
                this.tabField = value;
            }
        }
        
        /// <remarks/>
        public Account Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Account {
        
        private int idField;
        
        private string usernameField;
        
        private string passwordField;
        
        private int saltField;
        
        private Tab[] tabsField;
        
        private Share[] sharesField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int Salt {
            get {
                return this.saltField;
            }
            set {
                this.saltField = value;
            }
        }
        
        /// <remarks/>
        public Tab[] Tabs {
            get {
                return this.tabsField;
            }
            set {
                this.tabsField = value;
            }
        }
        
        /// <remarks/>
        public Share[] Shares {
            get {
                return this.sharesField;
            }
            set {
                this.sharesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RSSItemDTO {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string rSSLinkField;
        
        private int tabIDField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string RSSLink {
            get {
                return this.rSSLinkField;
            }
            set {
                this.rSSLinkField = value;
            }
        }
        
        /// <remarks/>
        public int TabID {
            get {
                return this.tabIDField;
            }
            set {
                this.tabIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckValidUsernameCompletedEventHandler(object sender, CheckValidUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckValidUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckValidUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddTabCompletedEventHandler(object sender, AddTabCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTabCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTabCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RemoveTabCompletedEventHandler(object sender, RemoveTabCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveTabCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveTabCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ShareTabCompletedEventHandler(object sender, ShareTabCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShareTabCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShareTabCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RenameTabCompletedEventHandler(object sender, RenameTabCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RenameTabCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RenameTabCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllTabsCompletedEventHandler(object sender, GetAllTabsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTabsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTabsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TabDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TabDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllSharedTabsCompletedEventHandler(object sender, GetAllSharedTabsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSharedTabsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSharedTabsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TabDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TabDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddRSSItemCompletedEventHandler(object sender, AddRSSItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddRSSItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddRSSItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RemoveRSSItemCompletedEventHandler(object sender, RemoveRSSItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveRSSItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveRSSItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllRSSItemsCompletedEventHandler(object sender, GetAllRSSItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllRSSItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllRSSItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RSSItemDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RSSItemDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRSSResultCompletedEventHandler(object sender, GetRSSResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRSSResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRSSResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRSSResultHTMLCompletedEventHandler(object sender, GetRSSResultHTMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRSSResultHTMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRSSResultHTMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllRSSPluginLinkCompletedEventHandler(object sender, GetAllRSSPluginLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllRSSPluginLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllRSSPluginLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591